// 台南 Tainan City FC — 2026/27 AFC Challenge League 團隊名單
// 若要新增/修改機票，編輯這個陣列即可
const ROSTER = [
  { role: "技術總監", name: "蕭永福", slug: "shiao-yungfu" },
  { role: "總教練",   name: "JOAO",   slug: "joao" },
  { role: "助理教練", name: "林全宗", slug: "lin-chuantsung" },
  { role: "秘書",     name: "簡佑昕", slug: "chien-yuhsin" },
  { role: "防護員",   name: "張國霖", slug: "chang-kuolin" },
  { role: "物理師",   name: "陳俊達", slug: "chen-chunda" },
  { role: "秘書",     name: "吳佩玲", slug: "wu-peiling" },
  { role: "媒體官",   name: "何詩敏", slug: "ho-shihmin" },
  { role: "隊長",     name: "吳俊青", slug: "wu-chunching" },
  { role: "隊員",     name: "王睿",   slug: "wang-ruei" },
  { role: "隊員",     name: "KIM SUNG KYUM", slug: "kim-sungkyum" },
  { role: "隊員",     name: "KIM SANG JUN",  slug: "kim-sangjun" },
  { role: "隊員",     name: "OH SE SIM",     slug: "oh-sesim" },
  { role: "隊員",     name: "KIM YOUNG GEUN",slug: "kim-younggeun" },
  { role: "隊員",     name: "WILKER", slug: "wilker" },
  { role: "隊員",     name: "PORTO",  slug: "porto" },
  { role: "隊員",     name: "KEVIN",  slug: "kevin" },
  { role: "隊員",     name: "OPOKU",  slug: "opoku" },
  { role: "隊員",     name: "劉和翰", slug: "liu-hohan" },
  { role: "隊員",     name: "蔡政儒", slug: "tsai-chengju" },
  { role: "隊員",     name: "潘文傑", slug: "pan-wenchieh" },
  { role: "隊員",     name: "王柏翰", slug: "wang-pohan" },
  { role: "隊員",     name: "林明偉", slug: "lin-mingwei" },
  { role: "隊員",     name: "馮少祺", slug: "fong-shaochi" },
  { role: "隊員",     name: "阿珞朴·古勵", slug: "adopkoli" },
  { role: "隊員",     name: "戴亞成", slug: "dai-yacheng" },
  { role: "隊員",     name: "李柏佑", slug: "li-boyou" },
  { role: "隊員",     name: "洪士程", slug: "hung-shihcheng" },
  { role: "隊員",     name: "陳羿玄", slug: "chen-yixuan" },
  { role: "隊員",     name: "郭博瑋", slug: "kuo-powei" },
  { role: "隊員",     name: "葉境均", slug: "yeh-chingchun" },
  { role: "隊員",     name: "李家樂", slug: "lee-chiale" }
];
